//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_BookStatistics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_01_BookStatistics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Лев Толстой
        ///	Война и мир
        ///
        ///
        ///	Том първи
        ///
        ///	Част първа
        ///
        ///	I
        ///
        ///	— Eh bien, mon prince, Gênes et Lucques ne sont plus que des apanages, des имения, de la famille Buonaparte. Non, je vous préviens, que si vous ne me dites pas, que nous avons la guerre, si vous vous permettez encore de pallier toutes les infamies, toutes les atrocités de cet Antichrist (ma parole, j’y crois) — je ne vous connais plus, vous n’êtes plus mon ami, vous n’êtes plus мой верен роб comme vous dites.*1 Е, здравейте, здравейте. Je v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lev_Tolstoj_Vojna_i_mir_24967 {
            get {
                return ResourceManager.GetString("Lev_Tolstoj_Vojna_i_mir_24967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Виктор Юго
        ///	Клетниците
        ///	Том първи
        ///
        ///
        ///	Великият и талантлив писател Виктор Юго е един от най-ярките представители на френската и световната култура.
        ///	Поет, драматург, романист, публицист, той е оставил голямо литературно наследство, което и до днес се чете с любов от милионите люде в цял свят.
        ///	„Клетниците“ е едно от най-известните му произведения. В него са отразени хуманистичните идеи на века и непримиримата борба против безчовечния закон в тогавашното общество.
        ///	С неподражаемо майсторство Виктор Ю [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Victor_Hugo_Kletnitsite_Tom_pyrvi_6101_b {
            get {
                return ResourceManager.GetString("Victor_Hugo_Kletnitsite_Tom_pyrvi_6101_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Виктор Юго
        ///	Клетниците
        ///	Том втори
        ///
        ///	Трета част
        ///	Мариус
        ///	(Продължение)
        ///
        ///	Книга седма
        ///	Котешки час
        ///
        ///	I
        ///	Рудници и рудокопачи
        ///
        ///	Всички човешки общества имат долен, _трети трюм_, както се казва в театрите. Обществената почва е подровена надлъж и нашир било за добро, било за зло. Тези подземни изкопи са едни над други. Има плитки и дълбоки галерии. И в тъмното подземие има горни и долни етажи. Понякога под цивилизацията стават срутвания, а ние тъпчем равнодушно и безгрижно по повърхността. Енцикло [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Victor_Hugo_Kletnitsite_Tom_vtori_6102_b {
            get {
                return ResourceManager.GetString("Victor_Hugo_Kletnitsite_Tom_vtori_6102_b", resourceCulture);
            }
        }
    }
}
